### ISSUE TITLE
Replace "Sponser" with "Sponsor"

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/app-catalog-dashboard#134]
Need to replace the text "sponser" anywhere it is used with "sponsor" instead.  This _includes_, but is not limited to, the image shown on the main ReadMe file.
![image](https://user-images.githubusercontent.com/8918397/200571658-00f02437-3801-4908-997e-a01c2bc5edd7.png)

**Comment by gudatta** [comment]
The configuration file was updated, so new solutions will have the correct field name. For existing solutions, just update the field label in the list settings.
