### ISSUE TITLE
Add Tenant App Catalog Flag

### ISSUE THREAD

**Issue by gudatta** [spsprinkles/app-catalog-dashboard#150]
Add a flag to allow the developer to select if they want to deploy the solution to the tenant app catalog or to a site collection. The default choice should be "True".

**Comment by Dade-R** [comment]
Agreed, as it doesn't seem logical that it would be deployed both tenant wide and still be in a SC App Catalog.

**Comment by gudatta** [comment]
The flag is really for the approver's team. It will not drive any other changes to the dashboard. The deployment buttons will be made available for both.
