### ISSUE TITLE
New Card View

### ISSUE THREAD

**Issue by gudatta** [spsprinkles/app-catalog-dashboard#169]
Create a new view that mirrors the modern view for the app store. A card should be used to include the app title, icon and description. This will help allow us to view the apps and search the description to better find apps.

**Comment by gudatta** [comment]
@Dade-R,
We are going to want to creaate another webpart for this. This will give the ability to view just the apps, and not have the interface for upload/edit/add/etc.

**Comment by mikevasiloff** [comment]
@gudatta rather than a whole new app, couldn't a JSON-formatted modern view of the library be used for this?

**Comment by gudatta** [comment]
Yes and no. The library view will need to be filtered by ContentType = "App" but then I believe you are limited in what you can do. If you double-click on the card, it will take you to the folder's files, which doesn't seem like you can the default behavior. We tried to use a JSON configuration on the view and removed the single click event, but the double click event is still there. If we can control the click event to take you somewhere else, or to the app's details, that would be ideal.

-Gunjan

**Comment by gudatta** [comment]
We are going to create a separate project for this concept.

**Comment by gudatta** [comment]
Separate project has been created here: https://github.com/spsprinkles/app-store
