### ISSUE TITLE
Action Button Label Does Not Match Dialog Title

### ISSUE THREAD

**Issue by chipce59** [spsprinkles/app-catalog-dashboard#198]
TITLE - Action Button Label Does Not Match Dialog Title

LOCATION - App Dashboard -> Details for individual App (View App Details) -> App Dashboard/App Name -> Action block buttons

ISSUE - When an Action button is selected where a dialog is displayed, the Action button label does not match the dialog title.  A partial label word is displayed between the app name and week day and the calendar date.

REASON FOR CHANGE - The mismatch can be confusing as to which dialog goes with which step in the review process.

EXAMPLE - When selecting the Action button "Edit Technical Review" the dialog title displays "App Name Review Tue Jan 31 2023
Revision to the dialog title for this example would be "App Name * Edit Technical Review * 31 JAN 2023"
This revision would fix the dialog title to match the Action button label, add separators for clarity, and use the proper military calendar format.

RESOURCES:
<img width="339" alt="Edit Technical Reivew Dialog" src="https://user-images.githubusercontent.com/72324377/217043932-1be2fac0-c79f-46dd-a00e-375a539a89cd.png">
<img width="223" alt="Edit Technical Reivew" src="https://user-images.githubusercontent.com/72324377/217043933-09d53aee-22e6-4be2-8147-1409cbc06cde.png">
<img width="339" alt="Edit Test Dialog" src="https://user-images.githubusercontent.com/72324377/217043935-84c4a266-9cb5-4b69-8a19-3d866640e186.png">
<img width="115" alt="Edit Test" src="https://user-images.githubusercontent.com/72324377/217043936-45567233-a9bf-4ebf-bf4f-d40be26938ac.png">

**Comment by Dade-R** [comment]
Date Completed is not being written either. We should update the Title of the Test Cases and Technical Reviews to use a Date field instead.
