### ISSUE TITLE
Support a .app package

### ISSUE THREAD

**Issue by Dade-R** [spsprinkles/app-catalog-dashboard#21]
Add support for a classic Add-in .app package. Consider filtering the file browser to only show supported app extension upon app upload dialog show.

**Comment by gudatta** [comment]
IMHO, we shouldn't implement this, as SPFx is the preferred and recommended method. @Dade-R, what is your opinion?

**Comment by Dade-R** [comment]
@gudatta - Based on customer feedback, this is not a priority and we are only focusing on SPFx webparts moving forward. Closing issue.

**Comment by mikevasiloff** [comment]
@gudatta & @Dade-R, on both the [SharePoint development overview](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-development-overview) and [SharePoint developer documentation](https://learn.microsoft.com/en-us/sharepoint/dev/) articles, "SharePoint Add-ins" is still prominently listed as one of the development options.

Using an add-in is still the only way to [Query a remote service using the web proxy in SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/query-a-remote-service-using-the-web-proxy-in-sharepoint) for example.  And add-ins are also just a solution-packaged file added to the App Catalog, so "supporting" them shouldn't be much different from what's already being done now with this Management Solution.

More info: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-add-ins

**Comment by gudatta** [comment]
@mikevasiloff, please feel free to reopen this and complete a PR on this for this enhancement of the older add-in model.
