### ISSUE TITLE
App icon not updated in App Catalog list

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/app-catalog-dashboard#220]
The dashboard solution can correctly extract the icon and set the URL as shown here:
![image](https://user-images.githubusercontent.com/8918397/220905274-06cc81c8-c6b8-4731-b71b-3e56b0c1ed4b.png)

However, it's not updating the **Icon** field in the App Catalog list itself:
![image](https://user-images.githubusercontent.com/8918397/220905447-08368225-833e-4a08-ac54-2c863e085e48.png)

Which means no icon is displayed in the out-of-the-box "app adding" experience:
![image](https://user-images.githubusercontent.com/8918397/220906027-424579b4-e799-4a15-9562-be12f5c0bad5.png)

![image](https://user-images.githubusercontent.com/8918397/220906153-681e8769-f25a-45a3-b6ca-da0b329c6455.png)

**Comment by gudatta** [comment]
https://github.com/spsprinkles/app-catalog-dashboard/pull/219

This PR is related to #213 which has a pretty big code update. I did notice an issue w/ the icon url fields and made a fix in this PR.
