### ISSUE TITLE
Delete Button Logic

### ISSUE THREAD

**Issue by gudatta** [spsprinkles/app-catalog-dashboard#261]
Approver/Admin should be able to delete the app at any state. The developer/sponsor of the app will be able to delete prior to "In Testing".

**Comment by Dade-R** [comment]
Agreed, although I think it would be good to prevent deletion if it's deployed. Maybe it has to be retracted first.

**Comment by gudatta** [comment]
The delete will try to retract by default from the test and prod sites. I don't delete the test web, since we have a separate one for that.
