### ISSUE TITLE
Unable to submit an app for review

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/app-catalog-dashboard#301]
Having a Test Case answer of _Tested in Teams: No_ results in the following when you try to submit an app for review:
![image](https://github.com/spsprinkles/app-catalog-dashboard/assets/8918397/35748dd9-d571-4406-b840-f0e32fc9e2e3)

Changing it to _N/A_ allowed me to submit.  This question is odd to me because the developer will not have been able to test the app in Teams within the DoD tenant because it would not have been deployed yet.

**Comment by gudatta** [comment]
I also noticed that the validation doesn't seem to work on certain field types. I believe we fixed this already and just need to update the library to the latest. I will make sure to do this and retest the validation.
