### ISSUE TITLE
Tenant Deployed Version

### ISSUE THREAD

**Issue by gudatta** [spsprinkles/app-catalog-dashboard#318]
When displaying the "Tenant Deployed", include the actual version # from the app catalog.

**Comment by gudatta** [comment]
We can only pull this info from the app catalog if the user has access to it. The other option is to store the version at the time of deployment to the tenant app catalog.

**Comment by gudatta** [comment]
Or we create an "Update Tenant App Catalog" button. Similar to the test site updates.

**Comment by gudatta** [comment]
Add a metadata field for tracking the deployed version and implement the update tenant button.

**Comment by mikevasiloff** [comment]
The App Catalog should be accessible (read permission) by all users in the tenant.  As such they should have access to read the value of the version field.

**Comment by Dade-R** [comment]
Make sure if a tenant version is already deployed, update the email to helpdesk indicating to update the tenant, rather than deploy to tenant.

**Comment by gudatta** [comment]
External users may not have access to the tenant app catalog, where all users do have this by default. We will move forward w/ loading the version from the tenant app catalog directly and show it for users w/ access.
