### ISSUE TITLE
Notifications for tenant deployers/help desk

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/app-catalog-dashboard#358]
Within the **Notifications** feature it seems there should also be a way to notify the "help desk" group responsible for [tenant] **deploying apps**. This is useful when an app has been approved but still hasn't been deployed and you need to send a message to "remind" those folks to take action.
![image](https://github.com/spsprinkles/app-catalog-dashboard/assets/8918397/47749bbe-3f04-4b15-a15b-5f4222f5cb3f)

**Comment by gudatta** [comment]
The configuration already has this built in to automatically email the appropriate team to complete their task.
