### ISSUE TITLE
Option to delete app

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/app-catalog-dashboard#359]
If an app has _not_ been deployed (it's in the "New" status or perhaps even the In Testing/Review steps), the developer should see an action/option to **Delete** the app.
![image](https://github.com/spsprinkles/app-catalog-dashboard/assets/8918397/119e7727-266c-431b-8c56-142d797aff4a)

This would address several use cases including:
1. App was uploaded by mistake
2. App was uploaded just as a test and needs to be deleted
3. App no longer needs to go through the process and should be removed

**Comment by gudatta** [comment]
Delete button exists and is part of the configuration. No code updates required for this issue, it's based on configuration.
